/**
 * The base URL for the ACTA SDK
 */
export type baseURL =
  | "https://acta.build/api/mainnet"
  | "https://acta.build/api/testnet";

export const DEFAULT_VAULT_CONTRACT_ID = {
  mainnet: "CAN2LSCQQGY6K2TZYZELHVNMXHMVNJBNII4RH2VTHMMJEWOTK2IFZYJF",
  testnet: "CDK642PLEPCQH7WUBLHYYSKRJZOUIRIPY7GXQRHOETGR2JJ76UK6SWLZ",
};

export const DEFAULT_ISSUANCE_CONTRACT_ID = {
  mainnet: "CB7SUT2VJUEIIQR4JZKSWTH3QMDY3NJWXP532BCRRSMKLH45UPN6O5AA",
  testnet: "CABQIR63YVKUBRSTEZFCXKJAR43PNF27WL2TAU67U5YMNABKZEWPHRDN",
};

export const DEFAULT_USDC_ISSUER = {
  mainnet: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
  testnet: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
};
